# change the followings to match your Github username and repo name
baseurl: "/logos-and-ergon" # the name of your github repo
url: "https://BCDigSchol.github.io" # the url of your github pages (change BCDigSchol to your username)

# site information used in page title, meta data etc.
title: Logos and Ergon
# description: Developed by Boston College

# csv file names - change if your csv files have different names
locations_csv: locations
authors_csv: authors
persons_csv: persons
sources_csv: sources

header_logo: assets/img/LogosErgon.png

# address for map tile server - change if you have your own server
map_tile_server: https://demotiles.maplibre.org/style.json

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# nav bar settings and links
nav-menu:
  - title: Home
    link: index
  - title: Readings
    link: readings
  - title: Selections
    link: selections
  - title: Subjects
    link: subjects
  - title: More Info
    submenu:
      - title: Sources
        link: sources
      - title: People
        link: people
      - title: Authors
        link: authors
      - title: Locations
        link: locations
  - title: About
    link: about

hide-footer: false # set to true to hide the footer
footer-message: Logos and Ergon | CC BY-NC License
footer-submessage:  By Mark Thatcher, with David J. Thomas & the Digital Scholarship Group, Boston College
footer-submessage-link: https://ds.bc.edu

# google-analytics: // if you want to use Google analytics, include your ID here

include:
  - _pages

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
    - jekyll-feed

collections:
  selections:
    output: true
    permalink: /selection/:name

defaults:
  - scope:
      path: ""
      type: selections
    values:
      layout: items/selections